# Generated by Django 4.2.6 on 2023-11-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_alter_artwork_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='path',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
