# Generated by Django 4.2.6 on 2023-11-06 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_artgroups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtGroups',
        ),
    ]
